---
- hosts: server
  gather_facts: no

  tasks:
    - file: path=/tmp/lilies-deploy state=directory
    - copy: src=../build/libs/lilies-1.2.3.jar dest=/tmp/lilies-deploy/lilies.jar
    - copy: src=Dockerfile dest=/tmp/lilies-deploy/Dockerfile

    - name: stop and delete obsolete containers
      docker:
        image: registry.gitlab.com/bochkovsa/lilies
        name: lilies
        state: absent

    - name: delete docker image
      docker_image:
        path: /tmp/lilies-deploy
        name: registry.gitlab.com/bochkovsa/lilies
        state: absent

    - name: build docker image
      docker_image:
        path: /tmp/lilies-deploy
        name: registry.gitlab.com/bochkovsa/lilies

    - name: clean
      file:
        path: /tmp/lilies-deploy
        state: absent

    - name: app container
      docker:
        name: lilies
        image: registry.gitlab.com/bochkovsa/lilies
        restart_policy: always
        state: running
        links:
          - postgres:postgres
        expose: 8080
