---
- hosts: 127.0.0.1
  tasks:
    - file: path=/tmp/lilies-deploy state=directory
    - copy: src=../target/lilies-1.2.2.jar dest=/tmp/lilies-deploy/lilies.jar
    - copy: src=Dockerfile dest=/tmp/lilies-deploy/Dockerfile

    - name: stop and delete obsolete containers
      docker:
        image: sb/lilies
        name: lilies
        state: absent

    - name: delete docker image
      docker_image:
        path: /tmp/lilies-deploy
        name: sb/lilies
        state: absent

    - name: build docker image
      docker_image:
        path: /tmp/lilies-deploy
        name: sb/lilies
        state: build

    - name: app container
      docker:
        name: lilies
        image: sb/lilies
        restart_policy: always
        state: running
        expose: 8080

    - name: clean
      file:
        path: /tmp/lilies-deploy
        state: absent
