---
- hosts: server
  gather_facts: no

  tasks:
    - file: path=/tmp/lilies-deploy state=directory
    - copy: src=../build/libs/lilies-1.3.1.jar dest=/tmp/lilies-deploy/lilies.jar
    - copy: src=Dockerfile dest=/tmp/lilies-deploy/Dockerfile

    - name: stop and delete obsolete containers
      docker_container:
        image: registry.gitlab.com/bochkovsa/lilies
        name: lilies
        state: absent

    - name: delete docker image
      docker_image:
        name: registry.gitlab.com/bochkovsa/lilies
        state: absent

    - name: build docker image
      docker_image:
        path: /tmp/lilies-deploy
        name: registry.gitlab.com/bochkovsa/lilies
        push: yes

    - name: drop docker image
      docker_image:
        name: registry.gitlab.com/bochkovsa/lilies
        state: absent
