---
- hosts: server
  tasks:
    - file: path=/tmp/lilies-deploy state=directory
    - copy: src=../build/libs/lilies-1.2.2.jar dest=/tmp/lilies-deploy/lilies.jar
    - copy: src=Dockerfile dest=/tmp/lilies-deploy/Dockerfile

    - name: stop and delete obsolete containers
      docker:
        image: sb-lilies
        name: lilies
        state: absent

    - name: delete docker image
      docker_image:
        path: /tmp/lilies-deploy
        name: sb-lilies
        state: absent

    - name: build docker image
      docker_image:
        path: /tmp/lilies-deploy
        name: sb-lilies
        pull: no
        state: present

    - name: app container
      docker:
        name: lilies
        image: sb-lilies
        restart_policy: always
        state: running
        links:
          - postgres:postgres
        expose: 8080

    - name: clean
      file:
        path: /tmp/lilies-deploy
        state: absent
